<!DOCTYPE html>
<html lang="en-GB">

  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<meta property="og:title" content="OCJP Chapter 6: Exceptions and Assertions" />
<meta property="og:description" content="Chapter 6 summary notes
" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://verric.github.io/2017/06/27/ocjp-chapter-6-exceptions-and-assertions/" />



<meta property="article:published_time" content="2017-06-27T14:28:09&#43;10:00"/>

<meta property="article:modified_time" content="2017-06-27T14:28:09&#43;10:00"/>











<meta name="twitter:card" content="summary"/><meta name="twitter:title" content="OCJP Chapter 6: Exceptions and Assertions"/>
<meta name="twitter:description" content="Chapter 6 summary notes
"/>
<meta name="generator" content="Hugo 0.30.2" />


    
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BlogPosting",
  "headline": "OCJP Chapter 6: Exceptions and Assertions",
  "url": "https://verric.github.io/2017/06/27/ocjp-chapter-6-exceptions-and-assertions/",
  "wordCount": "1891",
  "datePublished": "2017-06-27T14:28:09&#43;10:00",
  "dateModified": "2017-06-27T14:28:09&#43;10:00",
  "author": {
    "@type": "Person",
    "name": ""
  },
  "keywords": "programming, study-notes"
}
</script>



    <link rel="canonical" href="https://verric.github.io/2017/06/27/ocjp-chapter-6-exceptions-and-assertions/">

    <title>OCJP Chapter 6: Exceptions and Assertions | Verric&#39;s Blog</title>

    <!-- combined, minified CSS -->
    <link href="https://verric.github.iocss/style.css" rel="stylesheet" integrity="sha384-O8wjsnz02XiyrPxnhfF6AVOv6YLBaEGRCnVF&#43;DL3gCPBy9cieyHcpixIrVyD2JS5" crossorigin="anonymous">

    

    

    

    

  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="nav blog-nav">
          <a class="nav-link " href="https://verric.github.io"></a>
          
          
        </nav>
      </div>
    </div>

    <header class="blog-header">
      <div class="container">
        <h1 class="blog-title"><a href="https://verric.github.io" rel="home">Verric's Blog</a></h1>
        <p class="lead blog-description">Hugo tranquilpeak theme demo</p>
      </div>
    </header>

    <div class="container">
      <div class="row">
        <div class="col-sm-8 blog-main">

          


<article class="blog-post">
  <header>
    <h2 class="blog-post-title"><a href="https://verric.github.io/2017/06/27/ocjp-chapter-6-exceptions-and-assertions/">OCJP Chapter 6: Exceptions and Assertions</a></h2>
    <p class="blog-post-meta"><time datetime="2017-06-27T14:28:09&#43;10:00">Tue Jun 27, 2017</time> by  in 
<i class="fa fa-folder" aria-hidden="true"></i>&nbsp;<a href="https://verric.github.io/categories/programming" rel="category tag">programming</a>, <a href="https://verric.github.io/categories/study-notes" rel="category tag">study-notes</a>


<i class="fa fa-tag" aria-hidden="true"></i>&nbsp;<a href="https://verric.github.io/tags/programming" rel="tag">programming</a>, <a href="https://verric.github.io/tags/study-notes" rel="tag">study-notes</a>

</p>
  </header>
  <p>Chapter 6 summary notes
</p>

<!--toc-->

<h1 id="chapter-6-exceptions-and-assertions">Chapter 6: Exceptions and Assertions</h1>

<h2 id="chapter-goals">Chapter Goals:</h2>

<p><em>Exceptions and Assertions</em></p>

<ul>
<li>Use try-catch and throw statements</li>
<li>Use catch, multi-catch, and finally clauses</li>
<li>Use Autoclose resources with a try-with-resources statement</li>
<li>Create custom exceptions and Auto-closeable resources</li>
<li>Test invariants by using assertions</li>
</ul>

<h2 id="reviewing-exceptions">Reviewing Exceptions</h2>

<p>Exceptions are a way for Java and developers to handle situations where the program may fall off the &ldquo;happy path&rdquo; and how we should deal with scenarios.</p>

<h3 id="categories-of-exceptions">Categories of Exceptions</h3>

<p>There are two main exception type in Java;</p>

<p>Checked Exceptions -  must be declared and handled by the code
Unchecked Exceptions - not required to be handled by the code, also known as &ldquo;RuntimeExceptions&rdquo;</p>

<p>There are also <code>java.lang.Error</code> in which it is neither recommend nor expected for the developer to handle these scenarios as they generally indicate a non recoverable situation.</p>

<p><img src="http://i.imgur.com/tOEeCGx.png" alt="Exception class hierarchy" /></p>

<p>A checked exception is any exception that extends directly or in-directly from <code>Exception</code>  but not <code>RuntimeException</code>.</p>

<p>An unchecked exception is any exception that extends directly or in-directly from <code>RuntimeException</code></p>

<h3 id="ocjp-exceptions">OCJP Exceptions</h3>

<p>Reviewing from OCA there are exceptions to remember.</p>

<blockquote>
<p>ArithmeticException: Thrown by the JVM when code attempts to divide by zero.</p>

<p>ArrayIndexOutOfBoundsException: Thrown by the JVM when code uses an illegal index to access an array.</p>

<p>ClassCastException: Thrown by the JVM when an attempt is made to cast an object to a subclass of which it is not an instance.</p>

<p>IllegalArgumentException: Thrown by the program to indicate that a method has been passed an illegal or inappropriate argument.</p>

<p>NullPointerException: Thrown by the JVM when there is a null reference where an object is required.</p>

<p>NumberFormatException: Thrown by the program when an attempt is made to convert a string to a numeric type, but the string doesnâ€™t have an appropriate format.</p>
</blockquote>

<p>New checked exceptions in OCJP</p>

<ol>
<li>java.text.ParseException</li>
<li>java.io.IOException</li>
<li>java.io.FileNotFound Exception</li>
<li>java.io.NotSerializable Exception</li>
<li>java.sql.SQLException</li>
</ol>

<p>New runtime exceptions in OCJP</p>

<ol>
<li>java.lang.ArrayStoreException</li>
<li>java.time.DateTimeException</li>
<li>java.util.MissingResourceException</li>
</ol>

<p>As a general rule of thumb, any exceptions that deal with IO,databases and parsing are checked exceptions.</p>

<h3 id="try-statement">Try statement</h3>

<p>The try statement usually deals with code that could throw an exception, but may also be used to ensure certain code is called unconditionally as such, with the <code>try-finally</code> construct.</p>

<p>A <code>try</code> statement <em>MUST</em> be accompanied by  a <code>catch</code> or <code>finally</code> clause, or both. Having neither will fail to compile.</p>

<p>There are two (logical) rules to remember when dealing the try statement</p>

<blockquote>
<ol>
<li><p>Java checks the catch blocks in the order in which they appear. It is illegal to declare a subclass exception in a catch block that is lower down in the list than a superclass exception because it will be unreachable code.</p></li>

<li><p>Java will not allow you to declare a catch block for a checked exception type that cannot potentially be thrown by the try clause body. This is again to avoid unreachable code.</p></li>
</ol>
</blockquote>

<h3 id="throw-vs-throws">Throw vs Throws</h3>

<p>The <code>throws</code> keyword is used in a method declaration to denote that the method may throw an exception, forcing any calling code to either handle or re-declare the exception.</p>

<p>the <code>throw</code> keyword is used to actually to <em>throw</em> an exception.</p>

<pre><code class="language-java">public String getDataFromDatabase() throws SQLException {
  throw new UnsupportedOperationException();
}
</code></pre>

<h2 id="creating-custom-exceptions">Creating Custom Exceptions</h2>

<p>You can create your own exceptions by inheriting from <code>Exception</code> or <code>RuntimeException</code>.</p>

<pre><code class="language-java">class CannotSwimException extends Exception {}

class DangerInTheWater extends RuntimeException {}

class SharkInTheWaterException extends DangerInTheWater {}

class Dolphin {
  public void swim() throws CannotSwimException {
    // logic here
  }
}
</code></pre>

<p>Here <code>CannotSwimException</code> is a checked exception, as it directly extends from <code>Exception</code></p>

<p><code>DangerInTheWater</code> is runtime exception as it directly extends from <code>RuntimeException</code></p>

<p><code>SharkInTheWaterException</code> is a runtime exception as it indirectly extends from <code>RuntimeException</code></p>

<p>Any method that calls the Dolphin&rsquo;s <code>swim()</code> must either handle the <code>CannotSwimException</code> or themselves re-declare the exception.</p>

<p>There are three main constructors to use when extending exceptions:</p>

<pre><code class="language-java">public class CannotSwimException extends Exception {

  public CannotSwimException() {
    super();
  }

  public CannotSwimException(Exception e) {
    super(e);
  }

  public CannotSwimException(String message) {
    super(message);
  }
}
</code></pre>

<p>Here we can pass nothing, the exception or a message.</p>

<p>Any exception or message passed to the <code>Exception</code> constructor will be printed in the exceptions stack trace.</p>

<pre><code class="language-java">Exception in thread &quot;main&quot; CannotSwimException //empty constructor
at CannotSwimException.main(CannotSwimException.java:18)

Exception in thread &quot;main&quot; CannotSwimException: java.lang.RuntimeException //assume we called throw new CannotSwimException(new RuntimeException());
at CannotSwimException.main(CannotSwimException.java:19)
Caused by: java.lang.RuntimeException
... 1 more

Exception in thread &quot;main&quot; CannotSwimException: broken fin //assume we called throw new CannotSwimException(&quot;broken fin&quot;);
at CannotSwimException.main(CannotSwimException.java:20)
</code></pre>

<h2 id="using-multi-catch">Using Multi-catch</h2>

<p>Prior to Java 7, in order to catch multiple expiations in one try statement, the developer had to list multiple catch clauses, which code lead to convoluted code.</p>

<pre><code class="language-java">public static void main(String[] args) {
  try {
    Path path = Paths.get(&quot;dolphinsBorn.txt&quot;);
    String text = new String(Files.readAllBytes(path));
    LocalDate date = LocalDate.parse(text);
    System.out.println(date);

  } catch (DateTimeParseException e) {
    e.printStackTrace();
    throw new RuntimeException(e);

  } catch (IOException e) {
    e.printStackTrace();
    throw new RuntimeException(e);
  } 
}
</code></pre>

<p>Here we also have to remember that if exception is a related to another exception begin caught, the more specific (sub-class) exception must go first and the more generic exceptions be caught last (at the bottom).</p>

<p>As of Java 7 we can use multi catch to help clean things up</p>

<pre><code class="language-java">try {
    ...

  } catch (DateTimeParseException | IOException e) {
    e.printStackTrace();
    throw new RuntimeException(e);
}
</code></pre>

<p>There are a few rules when using multi-catch:</p>

<ol>
<li><p>When using multi-catch there can only be <em>ONE</em> variable name (in the code above it&rsquo;s, &lsquo;e&rsquo;) and it must be declared at the end of the catch clause.</p></li>

<li><p>Variables in a multi-catch clause are *effectively final   * meaning they can <em>NOT</em> be re-assigned.</p></li>

<li><p>Multiple exception types cant be related (other than exception), eg cant have <code>catch (FileNotFoundException | IOException e) { } // DOES NOT COMPILE</code></p></li>
</ol>

<h2 id="using-try-with-resources">Using Try with resources</h2>

<p>A try with resources statement is often used when dealing with resources that have to be closed after use such as; files, database connections, network connections.</p>

<p>Here since we want to close a resource we would always have to implement the <code>finally</code> clause to ensure the resource was properly closed.</p>

<pre><code class="language-java">public void oldApproach(Path path1, Path path2) throws IOException {
  BufferedReader in = null;
  BufferedWriter out = null;
  try {
    in = Files.newBufferedReader(path1);
    out = Files.newBufferedWriter(path2);
    out.write(in.readLine());

  } finally {
      if (in != null) in.close();
      if (out != null) out.close();
  }
}
</code></pre>

<p>Using try-with-resources the code above can be abbreviated to</p>

<pre><code class="language-java">public void newApproach(Path path1, Path path2) throws IOException {
  try (BufferedReader in = Files.newBufferedReader(path1); BufferedWriter out = Files.newBufferedWriter(path2)) {
    out.write(in.readLine());
  }
}
</code></pre>

<p>Here the <code>close()</code> methods are called implicitly.</p>

<h3 id="try-with-resources-basics">Try-With-Resources Basics</h3>

<p>With a try-with-resources statement, any resources that should be closed are placed in a parenthesis next to the try.</p>

<pre><code class="language-java">try(BufferedReader br = Files.newBufferReader();){}
</code></pre>

<p>A few rules about try-with-resources. (TWR)</p>

<ol>
<li>A TWR can have multiple <code>catch</code> clauses and up to  one <code>finally</code> clause</li>
<li>There is an implicit call the <code>close()</code> on the resource that is <em>ALWAYS</em> called before any developer programmed catch or finally clauses.</li>
<li>The resources scope is bound to the try statement, that is once the <code>try()</code> statements closing bracket is closed, the resource goes out of scope.</li>
<li>The resource <em>MUST</em> implement the <code>AutoCloseable</code> interface.</li>
<li>Java closes resources in the order they  were declared, if there are multiple resources.</li>
</ol>

<pre><code class="language-java">try (Scanner s = new Scanner(System.in)) {
  s.nextLine();
  } //try scope ends here and hence the scope of Scanner s.

  catch(Exception e) { 
    s.nextInt(); // DOES NOT COMPILE

  } finally{
    s.nextInt(); // DOES NOT COMPILE
}
</code></pre>

<h3 id="autocloseable">AutoCloseable</h3>

<p>In order for a class to be in the TRW statement, it must implement the <code>AutoCloseable</code> interface which has the following definition:</p>

<pre><code class="language-java">public void close() throws Exception;
</code></pre>

<p>As before the implementing class doesn&rsquo;t have to throw an exception, but it cna if it wants to.</p>

<pre><code class="language-java">public class TurkeyCage implements AutoCloseable {
  public void close() {
    System.out.println(&quot;Close gate&quot;);
  }

  public static void main(String[] args) {
    try (TurkeyCage t = new TurkeyCage()) {
    System.out.println(&quot;put turkeys in&quot;);
    }
  }
}
</code></pre>

<p>Note however if the method implementing <code>close</code> does throw a checked exception, then it must be handled in the calling code or re-declared, just like normal checked exceptions.</p>

<pre><code class="language-java">public class StuckTurkeyCage implements AutoCloseable {
  public void close() throws Exception {
    throw new Exception(&quot;Cage door does not close&quot;);
  }

  public static void main(String[] args) {
    try (StuckTurkeyCage t = new StuckTurkeyCage()) { // DOES NOT COMPILE, needs to handle `Exception`
    System.out.println(&quot;put turkeys in&quot;);
    }
  }
}
</code></pre>

<p>Ideally the <code>close()</code> method according to best practices, should;</p>

<ol>
<li>Be <a href="https://stackoverflow.com/questions/1077412/what-is-an-idempotent-operation">idempotent</a></li>
<li>Throw a more specific exception than <code>Exception</code>.</li>
</ol>

<h3 id="suppressed-exceptions">Suppressed Exceptions</h3>

<blockquote>
<p>When multiple exceptions are thrown, all but the first are called suppressed exceptions. The idea is that Java treats the first exception as the primary one and tacks on any that come up while automatically closing</p>
</blockquote>

<pre><code class="language-java">public class JammedTurkeyCage implements AutoCloseable {
public void close() throws IllegalStateException {
throw new IllegalStateException(&quot;Cage door does not close&quot;);
}

try (JammedTurkeyCage t = new JammedTurkeyCage()) {
  throw new IllegalStateException(&quot;turkeys ran off&quot;);
} 
catch (IllegalStateException e) {
  System.out.println(&quot;caught: &quot; + e.getMessage());
  for (Throwable t: e.getSuppressed())
  System.out.println(t.getMessage());
}

//output:
caught: turkeys ran off
Cage door does not close
</code></pre>

<p>Java closes resources in the order they  were declared.</p>

<pre><code class="language-java">try (JammedTurkeyCage t1 = new JammedTurkeyCage(); JammedTurkeyCage t2 = new JammedTurkeyCage()) {
  System.out.println(&quot;turkeys entered cages&quot;);
}
 catch (IllegalStateException e) {
    System.out.println(&quot;caught: &quot; + e.getMessage());
    for (Throwable t: e.getSuppressed())
    System.out.println(t.getMessage());
}

//output
turkeys entered cages
caught: Cage door does not close
Cage door does not close
</code></pre>

<p>Suppressed exceptions only apply to exceptions thrown from within the context of <code>try</code> or <code>TRW</code> statement, throwing an exception from a finally block or regular code must must handled like normal.</p>

<h2 id="re-throwing-exceptions">Re-throwing Exceptions</h2>

<p>//TODO not sure what to summarise, seems like standard java exception stuff</p>

<h2 id="working-with-assertions">Working With Assertions</h2>

<blockquote>
<p>An assertion is a Boolean expression that you place at a point in your code where you expect something to be true.</p>
</blockquote>

<h3 id="the-assert-statement">The Assert Statement</h3>

<p>The assert statement can take two forms.</p>

<pre><code class="language-java">assert boolean_expression;
assert boolean_expression: error_message;
</code></pre>

<p>If the assertion fails it throws an <code>AssertionError</code>. Here this is an <code>Error</code> not an <code>Exception</code>.</p>

<p>When using an assertion java throws the error and as such, the program usually ends.</p>

<p>If assertions are not enabled then Java simply <code>skips</code> over the asserting line.</p>

<h3 id="enabling-assertions">Enabling Assertions</h3>

<p>To enable assertions we must pass either:</p>

<ol>
<li>-enableassertions</li>
<li>-ea</li>
</ol>

<p>to the JVM.</p>

<p>Enabling assertions with no arguments makes assertions globally available except in the java core classes, however you can enable assertions for specific classes or packages.</p>

<p>For specific class</p>

<pre><code class="language-java">java -ea:com.wiley.demos.TestColors my.programs.Main
</code></pre>

<p>In a a package and sub-packages, here the 3 dots (&hellip;) means any classes and sub-packages</p>

<pre><code class="language-java">java -ea:com.wiley.demos... my.programs.Main
</code></pre>

<p>You can also use <code>-da</code> to disable assertions for certain classes or packages.</p>

<pre><code class="language-java">java -ea:com.wiley.demos... -da:com.wiley.demos.TestColors my.programs.Main
</code></pre>

<h3 id="using-assertions">Using Assertions</h3>

<p>Common assertion scenarios include:</p>

<blockquote>
<p>Internal Invariants You assert that a value is within a certain constraint. assert x &lt; 0 is an example of an internal invariant.</p>

<p>Class Invariants You assert the validity of an objectâ€™s state. Class invariants are typically private methods within the class that return a boolean . The upcoming Rectangle class demonstrates a class invariant.</p>

<p>Control Flow Invariants You assert that a line of code you assume is unreachable is never reached. The upcoming TestSeasons class demonstrates a control fl ow invariant.</p>

<p>Preconditions You assert that certain conditions are met before a method is invoked.</p>

<p>Post Conditions You assert that certain conditions are met after a method executes successfully.</p>
</blockquote>

<p>Using assertions in production is commonly advised against as triggering an assertion may will most likely cause the program to end, assertions are often used in debugging or situations where its critical the program does not reach  a certain state.</p>

  

  
  <hr>
  <footer>

  
    <section>
    <h4></h4>
    <nav class="nav sharing-icons">
      <a class="nav-item" href="https://www.facebook.com/sharer/sharer.php?u=https%3a%2f%2fverric.github.io%2f2017%2f06%2f27%2focjp-chapter-6-exceptions-and-assertions%2f" title="Share on Facebook"><span class="fa fa-facebook fa-2x" aria-hidden="true"></span></a>
      <a class="nav-item" href="https://plus.google.com/share?url=https%3a%2f%2fverric.github.io%2f2017%2f06%2f27%2focjp-chapter-6-exceptions-and-assertions%2f" title="Share on Google+"><span class="fa fa-google-plus fa-2x" aria-hidden="true"></span></a>
      <a class="nav-item" href="https://www.linkedin.com/shareArticle?mini=true&amp;url=https%3a%2f%2fverric.github.io%2f2017%2f06%2f27%2focjp-chapter-6-exceptions-and-assertions%2f" title="Share on LinkedIn"><span class="fa fa-linkedin fa-2x" aria-hidden="true"></span></a>
      <a class="nav-item" href="https://twitter.com/home?status=https%3a%2f%2fverric.github.io%2f2017%2f06%2f27%2focjp-chapter-6-exceptions-and-assertions%2f" title="Tweet this"><span class="fa fa-twitter fa-2x"></span></a>
    </nav>
  </section>

  

  
  </footer>
  

</article> 



        </div> <!-- /.blog-main -->

        <aside class="col-sm-3 ml-auto blog-sidebar">
  

  

  
</aside>


      </div> <!-- /.row -->
    </div> <!-- /.container -->

    <footer class="blog-footer">
      <p>
      
      Blog template created by <a href="https://twitter.com/mdo">@mdo</a>, ported to Hugo by <a href='https://twitter.com/mralanorth'>@mralanorth</a>.
      
      </p>
      <p>
      <a href="#"></a>
      </p>
    </footer>

  </body>

</html>
